branch-defaults:
  master:
    environment: udagram-app-env
    group_suffix: null
deploy:
  artifact: www/Archive.zip
environment-defaults:
  udagram-env:
    branch: null
    repository: null
global:
  application_name: udagram-app
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
